// include/fcemu/video_enhancer.h
#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <map>

namespace fcemu {

struct CRTEffect {
    float scanline_intensity = 0.5f;
    float curvature = 0.3f;
    float bloom_radius = 2.0f;
    float bloom_intensity = 0.3f;
    float chromatic_shift = 1.0f;
    bool enabled = true;
};

struct HDRParams {
    float exposure = 1.0f;
    float contrast = 1.0f;
    float saturation = 1.0f;
    float brightness = 0.0f;
    bool enabled = false;
};

enum class AAMode { None, FXAA, SMAA };

struct TextureReplacement {
    uint16_t bank;
    uint16_t tile_id;
    uint8_t palette_id;
    std::string file_path;
};

class VideoEnhancer {
public:
    VideoEnhancer();
    bool init();
    void shutdown();

    // Post-process the input 256x240 RGBA frame in-place style: returns a
    // pointer to an internal buffer with the result. When widescreen is
    // enabled, the output is 320x240 (extra columns generated by edge
    // replication + horizontal blur). Width/height of output are written
    // to *out_w / *out_h if non-null.
    const uint8_t* process(const uint8_t* rgba_256x240, int* out_w, int* out_h);

    // Legacy entrypoint kept for source compatibility — returns 1 on success.
    uint32_t process_frame(const uint8_t* rgba_256x240);
    const uint8_t* output() const { return out_buf_.empty() ? nullptr : out_buf_.data(); }
    int output_width()  const { return out_w_; }
    int output_height() const { return out_h_; }

    void set_crt_params(const CRTEffect& params);
    void set_hdr_params(const HDRParams& params);
    void set_aa_mode(AAMode mode);
    bool load_texture_replacements(const std::string& preset_path);
    void enable_texture_replacement(bool enable);
    void enable_widescreen(bool enable);
    bool widescreen_enabled() const { return widescreen_; }
    void trigger_shake(float intensity, int duration_ms);
    void trigger_hit_flash();
    void set_passthrough(bool enable);

private:
    uint32_t input_texture_;
    uint32_t output_texture_;
    CRTEffect crt_;
    HDRParams hdr_;
    AAMode aa_mode_ = AAMode::None;
    bool widescreen_ = false;
    bool passthrough_ = false;
    std::map<uint32_t, uint32_t> replacement_textures_;
    bool texture_replacement_enabled_ = false;
    float shake_intensity_ = 0.0f;
    int shake_remaining_ms_ = 0;
    bool hit_flash_ = false;
    std::vector<uint8_t> out_buf_;
    int out_w_ = 256, out_h_ = 240;
    uint32_t load_texture(const std::string& path);
};

} // namespace fcemu
